config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'products#new'

    post 'bing_serch' => 'products#create', as: :bing
    get 'download/:id' => 'products#download', as: :download
    get 'products_all' => 'products#all', as: :all

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index

    @products = Product.order('id DESC').first 10
end
 def all
    @products = Product.order('id DESC')

 end

  def download
    zip_data = File.read("#{Rails.root}/public/uploads/reports/#{params[:id]}.csv")
    send_data(zip_data, type: 'application/zip', filename: "#{params[:id]}.csv")
  end

  # GET /products/1
  # GET /products/1.json

  # GET /products/new
  def new
    @product = Product.new
  end

  def destroy
  Product.find(params[:id]).destroy
   redirect_to products_path


  end

  def show
    @product = Product.find(params[:id]) rescue ""  
  end


  # GET /products/1/edit


  # POST /products
  # POST /products.json
def create
  if params[:search] && params[:keyword].present?
    @search_keyword = params[:search].split(',') - [""]

    # if @search_keyword.size > 1
    @search_keyword.each do |ks|

      @serach_k = ks
      searching(@serach_k)
      @product = Product.create(title: @title, description: @discription, url: @url, search: @serach_k)
    end

  # end
  else
    @search = params[:search]
    searching(@search)
    @product = Product.create(title: @title, description: @discription, url: @url, search: @search)
  end
        sleep(30)
        if request.path ==  "/bing_serch"
  redirect_to products_path
else
  redirect_to products_path
end

  end
end

def searching(search)

  client = Mechanize.new
  @title = []
  @url = []
  @discription = []
  (1..531).step(10) do |p|
    client.get("https://www.bing.com/search?q=#{search}&first=#{p}") do |page|
      document = Nokogiri::HTML::Document.parse(page.body)
      alldata = document.css('li.b_algo') rescue ""
      alldata.each do |ad|
        @title << ad.at('a').text  rescue ""
        @discription << ad.at('p').text rescue ""
        @url << ad.at('a')['href'].to_s  rescue ""
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bing</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: #00FF7F;">

<%= yield %>

</body>
<style type="text/css">
	table, th, td {
   border: 1px solid black;
}
</style>
</html>

app/views/products/_form.html.erb
<table align="center">
 <thead>
    <tr>
      <th>Single Search</th>
      <th>Keywords Search</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <tr>
  <td>
	<%= form_tag('/bing_serch') do  %>
	<%= search_field_tag 'search', nil, placeholder: "Enter keyword" %>
	  <div><%= submit_tag 'Search with single keyword' %></div>
	<% end %>
</td>
<td>
	<%= form_tag('/bing_serch') do  %>
	<%= search_field_tag 'search', nil, placeholder: "Enter keywords" %>
	    <%= hidden_field_tag 'keyword', "keyword"%>
	  <div><%= submit_tag 'Search with multiple keywords' %></div>
	<% end %>
	</td>	
	</tr>
</tbody>
</table>

app/views/products/all.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Listing Search Result</h1>

<table align="center", style="border: 1px solid black;">
  <thead>
    <tr>
      <!-- <th>Search</th> -->
      
      <th>Searched Title</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
  <% if @products.present? %>
    <% @products.each do |product| %>
        <% @title = JSON.parse(product.title.to_json, :quirks_mode => true) %>
        <% @description = JSON.parse(product.description.to_json, :quirks_mode => true) %>
        <% @url = JSON.parse(product.url.to_json, :quirks_mode => true) %>
        <tr></tr>
        <tr>
        <td><%= product.search %></td>
          <td><%= link_to 'Show', product_path(product) , style: "color: blue; text-decoration: none;"%></td>
        </tr>

        
        
    <% end  %>
  <% end %>
  </tbody>
</table>

<br>
        

<%= link_to 'New Search', new_product_path, style: "color: blue; text-decoration: none;" %>
<%= link_to 'View all', all_path, style: "color: blue; text-decoration: none;" %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product , style: "color: blue; text-decoration: none;" %> |
<%= link_to 'Back', products_path , style: "color: blue; text-decoration: none;" %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Listing Search Result</h1>

<table align="center", style="border: 1px solid black;">
  <thead>
    <tr>
      <!-- <th>Search</th> -->
      
      <th>Searched Title</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
  <% if @products.present? %>
    <% @products.each do |product| %>
        <% @title = JSON.parse(product.title) %>
        <% @description = JSON.parse(product.description) %>
        <% @url = JSON.parse(product.url) %>
        <tr></tr>
        <tr>
        <td><%= product.search %></td>
          <td><%= link_to 'Show', product_path(product) , style: "color: blue; text-decoration: none;"%></td>
        </tr>

        
        
    <% end  %>
  <% end %>
  </tbody>
</table>

<br>
        

<%= link_to 'New Search', new_product_path, style: "color: blue; text-decoration: none;" %>

app/views/products/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', products_path , style: "color: blue; text-decoration: none;" %>

app/views/products/show.html.erb
<%if @product.present?%>
<table style="border: 1px solid black;">
  <thead>
    <tr>
      <!-- <th>Search</th> -->
      
      <th>No fo records</th>
      <th>Title</th>
      <th>Description</th>
      <th>Url</th>



      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>


<% if @product.present? %>
        <% @title = JSON.parse(@product.title) %>
        <% @description = JSON.parse(@product.description) %>
        <% @url = JSON.parse(@product.url) %>
        <% (0..@title.count).each.with_index(1) do |i, index|%>
        <tr>
        <td><%= index%></td>
        <td><%= @title[i]%></td>
        <td><%= @description[i]%></td>
        <td><%= @url[i] %></td>
        </tr>
       <% end %>
        
  <% end %>

<%= link_to 'Back', products_path , style: "color: blue; text-decoration: none;" %>
<% end %>

<style type="text/css">
	table, th, td {
   border: 1px solid black;
}
</style>